apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-ui
    spec:
      containers:
        - name: example-ui
          image: index.docker.io/neethirocks/example-ui:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: example-ui-service
  labels:
    name: example-ui-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: example-ui
  type: ClusterIP
